### ISSUE TITLE
Addon caused lost connection to cloud and some apis

### ISSUE THREAD

**Issue by mpgoebel** [hassio-addons/addon-adguard-home#24]
# Problem/Motivation

After installing the add on, and restarting Hass I lost connection toy ecobee and darksky components as well as no connection to nabucasa.

## Expected behavior

Function without losing Hass functionality

## Actual behavior

The above stopped working until I uninstalled the addon.  I even tried turning all of the filtering off with no change.

## Steps to reproduce

Install, restart, check components and homeassistant cloud connections.

**Comment by frenck** [comment]
This happens if you ignore the first step in the installation manual of the add-on

![image](https://user-images.githubusercontent.com/195327/60382157-8a0a1d00-9a5f-11e9-971a-74c2dfd905d5.png)


https://github.com/hassio-addons/addon-adguard-home#installation

**Comment by mpgoebel** [comment]
I guess I don't understand the external dns portion, I have always had my router setting the cloudflare dns and not auto.  I know my Hass has a static IP.  Maybe the first needs some more detail.

**Comment by frenck** [comment]
This has nothing to do with your router. Please note, setting an IP fixed in your router is not the same as a static IP.
When configuring the Hass.io device with a static IP, you'll also set static IP addresses for the DNS. Make sure those IP addresses are static as well.

AdGuard is a DNS server, if you don't know what it is or how it works, I would advise you not to use it.
This requires some knowledge on networking.

**Comment by mpgoebel** [comment]
What should the static dns be for HA? Cloudflare or AdGuard?
