### ISSUE TITLE
Adguard add-on not working anymore

### ISSUE THREAD

**Issue by daften** [hassio-addons/addon-adguard-home#245]
# Problem/Motivation

Since this night AdGuard does NOT want to reply to DNS queries anymore. The plugin wasn't updated, I didn't change any settings in it either. If I look on the host os, Adguard is listening
```
tcp        0      0 172.30.32.1:53          0.0.0.0:*               LISTEN      9695/AdGuardHome
```

What data can I share to debug this? I'm honestly lost.

## Expected behavior

AdGuard to just work

## Actual behavior

Well, it doesn't work

## Steps to reproduce

Honestly, no idea

## Proposed changes

/

**Comment by ioannispelelis** [comment]
I have the same issue and it pretty much happened after installing 2021.9.0 (core) & supervisor-2021.08.1
Not sure if one or the other triggered this.
But i see that since i did the update i am unable to set a static IP that actuaylly holds and after a reboot of the host the supervisor comes back to dhcp
As such it looks lik adguard is not binding to the interface since it is not in static? just a thought..

**Comment by ioannispelelis** [comment]
Ok so i restarted the OS
under supervisor tab I reset ip of OS  to dhcp..
tried to reset the IP to manual.. it failed
reset again to dhcp
and then back again with manual (using external dns in the os configuration)
then restarted adguard addon and now it tied to the network interface again and it works
However from what I can see it looks like each time i reboot the OS the IP comes back to DHCP.. which will make Adguard fail again and need to do this process all over..

**Comment by shirou93** [comment]
Today my adguard home stop listening. supervisor-2021.09.6. No updates no changes.

**Comment by stevehop** [comment]
Same here, updated to supervisor-2021.09.6 and adguard DNS over https has stopped working. Will attempt to restore the supervisor to 2021.09.4 tomorrow to see if that resolves it. So far I restored known working snapshots of the Adguard addon itself and Home Assistant but neither did the trick

**Comment by ioannispelelis** [comment]
I am on 2021.9.7 and Adguard works. BUT each time I shutdown or reboot my VM I have to reput the IP of homeassistant to static (instead of DHCP) so Adguard works.. 
I can see in Adguard when it does not work that instead of showing two ups in the setup guide (one being the real IP of HA on the nework and the other IP used internally by HA or docker i don't known) it only shows one of them (the internal IP of HA)
When I switch to static IP on HA and reboot Adguard it then ties to the two ips and Adguard works again...
![IMG_20210930_205245](https://user-images.githubusercontent.com/57101460/135513971-9a9739ed-e964-4310-9a82-27dc3a1a40ce.jpg)

**Comment by shirou93** [comment]
> Same here, updated to supervisor-2021.09.6 and adguard DNS over https has stopped working. Will attempt to restore the supervisor to 2021.09.4 tomorrow to see if that resolves it. So far I restored known working snapshots of the Adguard addon itself and Home Assistant but neither did the trick

on old supervisor will start work properly?

**Comment by stevehop** [comment]
> on old supervisor will start work properly?

I haven't been able to successfully roll back, I restored an old back up but it automatically upgraded to 2021.09.06.

I've done some more investigating and found that it's actually DoT that's broken for me and only for Android devices, I've tested using the Windows YogaDNS software and it still connects to my DoT server fine, other DoT servers like Adguard's hosted server still work fine with my Android devices

**Comment by Stooovie** [comment]
Just stopped filtering for me too. Nothing I can do brings the proper filtering back. SOME stuff is going through it but not everything. nslookup shows HA's IP as expected.
