### ISSUE TITLE
Adguard takes sometimes too much time to resolve IP addresses 

### ISSUE THREAD

**Issue by nicolasvila** [hassio-addons/addon-adguard-home#259]
# Problem/Motivation

AdGuard is my home DNS server and use it on every devices on the LAN. After fresh start, it works pretty well and response time is <5ms 'I suppose when the address is in Adguard cache)
Reponse times drop after a while.... Too many requests to handle? No error in logs, just a massive slowdown with response times up to  x1000

## Expected behavior

AdGuard should answer DNS requests with acceptable response time without any intervention

## Actual behavior

After a few hours, days,... (it depends) Adguard response time increases dramatically and DNS solving does not work as expected anymore. Service is too slow (>4-5sec)
After restart of the addon, service is back to normal, with correct response times.

## Steps to reproduce

Just wait until AdGuard becomes unresponsive. 

## Proposed changes

This problem is occuring since a few months (maybe spring)

**Comment by LordNex** [comment]
I’ve noticed some of this as well. Giving I have satellite internet so my hops are high anyway. But it does seem to bog down if not restarted daily



On Oct 5, 2021, at 3:04 AM, Nicolas VILA ***@***.***> wrote:

﻿

Problem/Motivation

AdGuard is my home DNS server and use it on every devices on the LAN. After fresh start, it works pretty well and response time is <5ms 'I suppose when the address is in Adguard cache)
Reponse times drop after a while.... Too many requests to handle? No error in logs, just a massive slowdown with response times up to x1000

Expected behavior

AdGuard should answer DNS requests with acceptable response time without any intervention

Actual behavior

After a few hours, days,... (it depends) Adguard response time increases dramatically and DNS solving does not work as expected anymore. Service is too slow (>4-5sec)
After restart of the addon, service is back to normal, with correct response times.

Steps to reproduce

Just wait until AdGuard becomes unresponsive.

Proposed changes

This problem is occuring since a few months (maybe spring)

**Comment by Razer0123** [comment]
Has anyone find a solution? i cannot understand if it's a DNS problem, an hardware problem or an addon problem

**Comment by wouwal** [comment]
For me the solution was changing the upstream DNS server (under DNS settings) from the standard Adguard DNS to another. I have chosen cloudflare, but there are many. There's a link on the DNS settings page of Adguard. Since then, no noticable delays or errors anymore!

**Comment by Razer0123** [comment]
> For me the solution was changing the upstream DNS server (under DNS settings) from the standard Adguard DNS to another. I have chosen cloudflare, but there are many. There's a link on the DNS settings page of Adguard. Since then, no noticable delays or errors anymore!

Tried changing my server to cloudflare but still have issues, works fine at first, then becomes slower

**Comment by Razer0123** [comment]
Tried uninstalling and installing Adguard again, i don't want to talk too soon but seems like the issue is solved now

**Comment by Razer0123** [comment]
I can confirm this still happens, all you have to do is take off the power once the addon is running, at the next startup problem will appear
