### ISSUE TITLE
local_domain_name support

### ISSUE THREAD

**Issue by hkrob** [hassio-addons/addon-adguard-home#410]
Apologies if already answered (I have checked but haven't found...) - 
is it possible to set local_domain_name for the add-on?

The default domain name is .lan but I would like to set it to something else.

This is documented here https://github.com/AdguardTeam/AdGuardHome/wiki/Configuration#configuration-file

local_domain_name — The domain name that AdGuard Home's DHCP server uses for hostnames of its clients. The default value, which is also set when this value is empty, is lan. So, if you have a machine called myhost in your network, and AdGuard Home is this network's DHCP server, the hostname of that machine is myhost.lan.

**Comment by plord12** [comment]
I would like to second this request ( see https://community.home-assistant.io/t/is-there-are-way-to-get-adguard-home-dns-and-dhcp-to-work-together/566818 )

In addition, I would also like to set the DHCP domain search list (option 119) so that client would work without specify the domain ... see https://github.com/AdguardTeam/AdGuardHome/wiki/DHCP.  I believe this would be -

```
'options':
- '119 text homedomain'
```
