### ISSUE TITLE
Provide an option to use default login dashboard

### ISSUE THREAD

**Issue by thomaspetit** [hassio-addons/addon-adguard-home#488]
# Problem/Motivation

Currently the login page of adguard has been override in favor of integrating with the user management system of Home Assistant. For 99% of the people I think that this is enough. Sadly it doesn't allow me to integrate this adguard instance within my Kubernetes cluster.

The [external-dns](https://github.com/kubernetes-sigs/external-dns) application running in my kubernetes cluster(s) allow me to update an adguard instance so that new DNS records are automatically published. For this application to work you either need to use unauthenticated or authenticated access. The latter will use the built-in Adguard login screen.

## Actual behavior

We can only set `leave_front_door_open` or use the built-in authentication mechanism implemented with Home Assistant

## Proposed changes

Provide an option to use the built-in login by Adguard (non-default option) on top of the `leave_front_door_open` feature

**Comment by sinclairpaul** [comment]
Nothing has been "overridden" the AdGuard auth isn't configured because it is handled by the reverse proxy in front of it (I don't believe Adguards default is to configure auth).

As it is driven by configuration of the json, how would users then configure it?, it isn't something that the addon needs.

I don't really understand why the auth should be required for the external-dns provider, adguard can run without it.  I'd also ask if the addon doesn't meet your needs why wouldn't you just run it in k8s anyway?
